version: '3.8'

services:
  database:
    container_name: postgresql-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
       - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql:
