name: Build Test And Deploy

on:
  - pull_request
  - push

jobs:
  dotnet_build_and_test:
    name: Build And Test .NET 7.0 Projects
    runs-on: ubuntu-latest

    steps:
    - name: Checkout To Branch
      uses: actions/checkout@v3

    - name: Setup .NET 7.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore .NET Dependencies
      run: dotnet restore

    - name: Build .NET
      run: dotnet build --no-restore

    - name: Run .NET Tests
      run: dotnet test --no-restore --verbosity normal

  # nodejs_build_and_test:
  #   needs: dotnet_build_and_test
  #   name: Build And Test Node.js 18.x.x Projects
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: src/ClientApp/

  #   steps:
  #   - name: Checkout To Branch
  #     uses: actions/checkout@v3

  #   - name: Setup Node.js 18.x.x
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 18.x

  #   - name: Install Node.js
  #     run: npm ci

  #   - name: Build Node.js
  #     run: npm run build
