name: Build And Test

on:
  - pull_request
  - push

jobs:
  dotnet_build_and_test:
    name: Build And Test .NET 7.0 Projects
    runs-on: ubuntu-latest

    steps:
    - name: Checkout To Branch
      uses: actions/checkout@v3

    - name: Setup .NET 7.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore .NET Dependencies
      run: dotnet restore

    - name: Build .NET
      run: dotnet build --no-restore

    - name: Run .NET Tests
      run: dotnet test --no-restore --verbosity normal
